import {
  Palette,
  Medal,
  Sparkles,
  BriefcaseBusiness,
  Laugh,
  ChefHat,
  Hammer,
  GraduationCap,
  Clapperboard,
  Rocket,
  Users,
  Shirt,
  ChartNoAxesCombined,
  Dumbbell,
  Utensils,
  Gamepad2,
  Landmark,
  House,
  Coffee,
  BookOpen,
  Brain,
  Smartphone,
  Music,
  Trees,
  Baby,
  Wallet,
  PawPrint,
  Camera,
  Mic,
  Star,
  ListChecks,
  Heart,
  Footprints,
  Droplets,
  Trophy,
  Cpu,
  Plane,
  Fingerprint,
  Leaf,
  Flower2,
  Tags,
  type LucideIcon,
} from "lucide-react";
const icons: Record<string, LucideIcon> = {
  Art: Palette,
  Athlete: Medal,
  Beauty: Sparkles,
  Business: BriefcaseBusiness,
  Comedy: Laugh,
  Cooking: ChefHat,
  DIY: Hammer,
  Education: GraduationCap,
  Entertainment: Clapperboard,
  Entrepreneurship: Rocket,
  Family: Users,
  Fashion: Shirt,
  Finance: ChartNoAxesCombined,
  Fitness: Dumbbell,
  Food: Utensils,
  Gaming: Gamepad2,
  History: Landmark,
  Home: House,
  Lifestyle: Coffee,
  Literature: BookOpen,
  "Mental Health": Brain,
  "Mobile Gaming": Smartphone,
  Music: Music,
  Outdoors: Trees,
  Parenthood: Baby,
  "Personal Finance": Wallet,
  Pets: PawPrint,
  Photography: Camera,
  Podcast: Mic,
  "Pop Culture": Star,
  Productivity: ListChecks,
  Relationship: Heart,
  Running: Footprints,
  Skincare: Droplets,
  Sports: Trophy,
  Tech: Cpu,
  Travel: Plane,
  "True Crime": Fingerprint,
  Wellness: Leaf,
  Yoga: Flower2,
};
export function NicheIcon({
  niche,
  size = 16,
}: {
  niche: string;
  size?: number;
}) {
  const Icon = icons[niche] ?? Tags;
  return <Icon size={size} className="shrink-0" aria-hidden="true" />;
}
