export const BANK_OPTIONS = [
    { name: 'Affin Bank', swiftCode: 'PHBMMYKL', logo: 'https://raw.githubusercontent.com/SnorSnor9998/Payment-Icon/master/Banks/AffinBank/AffinBank_V1_SQU.svg' },
    { name: 'Agrobank', swiftCode: 'AGOBMYKL', logo: 'https://logosandtypes.com/wp-content/uploads/2020/06/agrobank.png' },
    { name: 'Al Rajhi Bank', swiftCode: 'RJHIMYKL', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEMA24xQ5OGD5C_unOUGFm-AC12UqAZrbJRw&s' },
    { name: 'Alliance Bank', swiftCode: 'MFBBMYKL', logo: 'https://raw.githubusercontent.com/SnorSnor9998/Payment-Icon/master/Banks/AllianceBank/AllianceBank_V1_SQU.svg' },
    { name: 'AmBank', swiftCode: 'ARBKMYKL', logo: 'https://raw.githubusercontent.com/SnorSnor9998/Payment-Icon/master/Banks/AmBank/AmBank_V1_SQU.svg' },
    { name: 'Bank Islam Malaysia', swiftCode: 'BIMBMYKL', logo: 'https://raw.githubusercontent.com/SnorSnor9998/Payment-Icon/master/Banks/BankIslam/BankIslam_V1_SQU.svg' },
    { name: 'Bank Muamalat', swiftCode: 'BMMBMYKL', logo: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg8j9euE1Zu9r5TOWxAviKY-cTRdaTjlZ5aMpRbpvUBlN1w4KnYi8j1lJcaYt21WDG2NzInQPp-ZIUnNIYtyFusWRTxwXyC_VKclw86af_-C0oNwHtqvlKX9Yh_95t7jLrg9-OXC4LajA/s1600/LOGO+BANK+MUAMALAT.jpg' },
    { name: 'Bank Rakyat', swiftCode: 'BKRMMYKL', logo: 'https://raw.githubusercontent.com/SnorSnor9998/Payment-Icon/master/Banks/BankRakyat/BankRakyat_V1_SQU.svg' },
    { name: 'BSN (Bank Simpanan Nasional )', swiftCode: 'BSNAMYK1', logo: 'https://raw.githubusercontent.com/SnorSnor9998/Payment-Icon/master/Banks/BSN/BSN_V1_SQU.svg' },
    { name: 'CIMB Bank', swiftCode: 'CIBBMYKL', logo: 'https://raw.githubusercontent.com/SnorSnor9998/Payment-Icon/master/Banks/Cimb/Cimb_V1_SQU.svg' },
    { name: 'Citibank', swiftCode: 'CITIMYKL', logo: 'https://img.icons8.com/color/1200/citibank.jpg' },
    { name: 'Hong Leong Bank', swiftCode: 'HLBBMYKL', logo: 'https://raw.githubusercontent.com/SnorSnor9998/Payment-Icon/master/Banks/HongLeongBank/HongLeongBank_V1_SQU.svg' },
    { name: 'HSBC Bank', swiftCode: 'HBMBMYKL', logo: 'https://raw.githubusercontent.com/SnorSnor9998/Payment-Icon/master/Banks/HSBC/HSBC_V1_SQU.svg' },
    { name: 'Kuwait Finance House', swiftCode: 'KFHOMYKL', logo: 'https://www.kfh.com.my/dam/jcr:55529bc9-2ad5-4959-8595-d833303b8b88/kfhm-logo.png' },
    { name: 'Maybank (Malayan Banking )', swiftCode: 'MBBEMYKL', logo: 'https://raw.githubusercontent.com/SnorSnor9998/Payment-Icon/master/Banks/Maybank/MayBank_V1_SQU.svg' },
    { name: 'MBSB Bank', swiftCode: '', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcGYvy4oKtI8SRJvW5_jSSn8oailuEhDn4xQ&s' },
    { name: 'OCBC Bank', swiftCode: 'OCBCMYKL', logo: 'https://raw.githubusercontent.com/SnorSnor9998/Payment-Icon/master/Banks/OCBC/OCBC_V1_SQU.svg' },
    { name: 'Public Bank Berhad', swiftCode: 'PBBEMYKL', logo: 'https://raw.githubusercontent.com/SnorSnor9998/Payment-Icon/master/Banks/PublicBank/PublicBank_V1_SQU.svg' },
    { name: 'RHB Bank', swiftCode: 'RHBBMYKL', logo: 'https://raw.githubusercontent.com/SnorSnor9998/Payment-Icon/master/Banks/RHB/RHB_V1_SQU.svg' },
    { name: 'Standard Chartered', swiftCode: 'SCBLMYKX', logo: 'https://raw.githubusercontent.com/SnorSnor9998/Payment-Icon/master/Banks/StandardChartered/StandardChartered_V1_SQU.svg' },
    { name: 'UOB Bank', swiftCode: 'UOVBMYKL', logo: 'https://raw.githubusercontent.com/SnorSnor9998/Payment-Icon/master/Banks/UOB/UOB_V1_SQU.svg' },
];
